# Generated by Django 2.1.3 on 2018-11-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditos',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='creditos',
        ),
    ]
