# Generated by Django 2.1.3 on 2018-11-21 01:53

import cartera.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_usuario_administrador_usuario_operador'),
        ('cartera', '0002_auto_20181120_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indentificacion', models.IntegerField(validators=[cartera.models.validate_even], verbose_name='Identificacion del cliente')),
                ('valor', models.IntegerField()),
                ('Tiempo_credito', models.IntegerField()),
                ('Fecha_compra', models.DateField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('Fecha_max_pago', models.DateTimeField(null=True, verbose_name='Fecha max de pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
            options={
                'verbose_name': 'credito',
                'verbose_name_plural': 'creditos',
                'ordering': ['Fecha_compra'],
            },
        ),
    ]
